// Source unique des 42 pages WAR TABLE.

export interface PageDef { id: string; label: string; icon: string; cat: string; }

export const WAR_TABLE_PAGES: PageDef[] = [
  { cat: 'Documentation', id: 'mode-emploi',       label: "Mode d'emploi",          icon: '📖' },
  { cat: 'Documentation', id: 'checkup',           label: 'Check-up lancement',     icon: '🚀' },
  { cat: 'Documentation', id: 'routine',           label: 'Routine quotidienne',    icon: '📅' },
  { cat: 'Documentation', id: 'daily',             label: 'Daily Stand-up',         icon: '🗣' },
  { cat: 'Documentation', id: 'nouveau-projet',    label: 'Nouveau projet',         icon: '🆕' },
  { cat: 'Documentation', id: 'regen-alloc',       label: 'Régénérer Allocation',   icon: '🔄' },
  { cat: 'Guides Scrum',  id: 'dod',               label: 'DoD',                    icon: '📋' },
  { cat: 'Guides Scrum',  id: 'dor',               label: 'DoR',                    icon: '📥' },
  { cat: 'Guides Scrum',  id: 'templates',         label: 'Templates Tickets',      icon: '📑' },
  { cat: 'Dashboards',    id: 'dashboard',         label: 'Dashboard Global',       icon: '📊' },
  { cat: 'Dashboards',    id: 'dashboard-param',   label: 'Dashboard Paramétré',    icon: '🎛' },
  { cat: 'Dashboards',    id: 'dashboard-legacy',  label: 'Dashboard',              icon: '📈' },
  { cat: 'Communication', id: 'vue-stakeholder',   label: 'Vue Stakeholder',        icon: '👁' },
  { cat: 'Communication', id: 'stakeholders',      label: 'Stakeholders',           icon: '😊' },
  { cat: 'Communication', id: 'export-stakeholder',label: 'Export Stakeholder',     icon: '📤' },
  { cat: 'Multi-Projets', id: 'projets',           label: 'Projets',                icon: '🗂' },
  { cat: 'Multi-Projets', id: 'phases',            label: 'Phases',                 icon: '🧩' },
  { cat: 'Multi-Projets', id: 'allocation',        label: 'Allocation Multi-Projets', icon: '📐' },
  { cat: 'Multi-Projets', id: 'charge',            label: 'Charge Multi-Projets',   icon: '⚖' },
  { cat: 'Multi-Projets', id: 'capacity',          label: 'Capacity Planning',      icon: '👥' },
  { cat: 'Config',        id: 'parametres',        label: 'Paramètres',             icon: '⚙' },
  { cat: 'Backlogs',      id: 'backlog',           label: 'Backlog',                icon: '📜' },
  { cat: 'Backlogs',      id: 'backlog-tma',       label: 'Backlog TMA',            icon: '🔧' },
  { cat: 'Cérémonies',    id: 'sprint-planning',   label: 'Sprint Planning',        icon: '🎯' },
  { cat: 'Cérémonies',    id: 'sprint-review',     label: 'Sprint Review',          icon: '🔍' },
  { cat: 'Cérémonies',    id: 'retros',            label: 'Rétrospectives',         icon: '🔄' },
  { cat: 'Cérémonies',    id: 'detail-tickets',    label: 'Détail tickets',         icon: '🗒' },
  { cat: 'Cérémonies',    id: 'vue-sprint',        label: 'Vue par Sprint',         icon: '📋' },
  { cat: 'Cérémonies',    id: 'sprints',           label: 'Sprints',                icon: '🏃' },
  { cat: 'Métriques',     id: 'burndown',          label: 'Burndown',               icon: '📉' },
  { cat: 'Métriques',     id: 'cfd-velocity',      label: 'CFD & Velocity',         icon: '📊' },
  { cat: 'Pilotage',      id: 'roadmap',           label: 'Roadmap',                icon: '🗺' },
  { cat: 'Pilotage',      id: 'dependances',       label: 'Dépendances',            icon: '🔗' },
  { cat: 'Pilotage',      id: 'tech-debt',         label: 'Tech Debt',              icon: '💳' },
  { cat: 'Pilotage',      id: 'knowledge',         label: 'Knowledge Base',         icon: '📚' },
  { cat: 'Personnel',     id: 'overtime',          label: 'Heures Sup',             icon: '⏰' },
  { cat: 'Planning',      id: 'gantt',             label: 'Gantt',                  icon: '📅' },
  { cat: 'Planning',      id: 'calendrier',        label: 'Calendrier',             icon: '🗓' },
  { cat: 'Vue Externe',   id: 'vue-reviewer',      label: 'Vue Reviewer',           icon: '🔎' },
  { cat: 'Risques',       id: 'risks',             label: 'Risques',                icon: '⚠' },
  { cat: 'Risques',       id: 'lessons',           label: 'Lessons Learned',        icon: '✨' },
  { cat: 'Listes',        id: 'listes',            label: 'Listes',                 icon: '🔒' },
];
